[package]
name = "wc_jake_toy"
version = "0.1.0"
authors = ["jake"]
edition = "2018"
description = "A toy version of word count"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
